[tools]
ollama = "latest"
python = { version='3' }
uv = "latest"

[settings]
experimental = true
python.uv_venv_auto = true

[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Automatic virtualenv activation
_.python.venv = { path = ".venv" , create = true }
LC_ALL = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[tasks.setup]
description = "Setup development environment"
run = [
    "uv pip install -r requeriments.txt"
]

[tasks.start]
description = "Start development environment"
run = [
    "jupyter lab --ip=0.0.0.0 --no-browser --allow-root"
]

[tasks.ollama-serve]
description = "Start Ollama server"
run = [
    "ollama serve"
]
